"""
booking.py

Pydantic schemas for creating and reading Booking data within the
Technician Booking System. These schemas define the data validation
and structure for incoming requests (e.g., booking creation) and
outgoing responses (e.g., booking details).
"""

from datetime import datetime
from pydantic import BaseModel, Field


class BookingBase(BaseModel):
    """
    Base schema for Booking-related data.

    Attributes:
        customer_name (str): The name of the customer who made the booking.
        technician_name (str): The name of the assigned technician.
        profession (str): The technician's profession (e.g., 'Plumber').
        start_time (datetime): The scheduled start time of the booking.
    """

    customer_name: str = Field(..., example="John Smith")
    technician_name: str = Field(..., example="Jane Doe")
    profession: str = Field(..., example="Electrician")
    start_time: datetime = Field(..., example="2023-12-01T09:00:00")


class BookingCreate(BookingBase):
    """
    Schema for creating a new booking.

    The booking ID and end_time will be generated by the service layer.
    """

    class Config:
        schema_extra = {
            "example": {
                "customer_name": "Alice Johnson",
                "technician_name": "Mark Roberts",
                "profession": "Welder",
                "start_time": "2024-01-15T14:00:00"
            }
        }


class BookingResponse(BookingBase):
    """
    Schema for reading (retrieving) a Booking.

    Attributes:
        id (str): Unique identifier (UUID) for the booking.
        end_time (datetime): Calculated as one hour after start_time by the service layer.
    """

    id: str = Field(..., example="bdff5803-7c45-4fac-9848-234dfc36da06")
    end_time: datetime = Field(..., example="2024-01-15T15:00:00")

    class Config:
        schema_extra = {
            "example": {
                "id": "bdff5803-7c45-4fac-9848-234dfc36da06",
                "customer_name": "Alice Johnson",
                "technician_name": "Mark Roberts",
                "profession": "Welder",
                "start_time": "2024-01-15T14:00:00",
                "end_time": "2024-01-15T15:00:00"
            }
        }
